---
author: Cail Daley
standalone: true
fontsize: 12pt
geometry: margin=1in


csl: /src/.panrun/aastex63/ApJ.csl
link-citations : true
linkcolor: "MidnightBlue"
citecolor: "MidnightBlue"
urlcolor: "MidnightBlue"

output:
    latex:
        to: latex
        filter:
            - pandoc-crossref
            - pandoc-citeproc
        pdf-engine : xelatex
        include-in-header: /src/.panrun/application_header.tex
---
