standalone: true
fontsize: 12pt
geometry: margin=1in
title: HI
output:
    latex:
        to: latex
        pdf-engine : xelatex
        include-in-header: /src/.panrun/headers/default_header.tex
    html:
        to: html
